#!/usr/bin/env python3
"""Translate guide sections for all language files."""
import json
import os
import copy

MESSAGES_DIR = os.path.expanduser("~/Developer/dopplerLanding/messages")

# Complete translations for all 18 languages
# Only the guide section values that need translating

translations = {
    "de": {
        "title": "Einrichtungsanleitung",
        "subtitle": "In wenigen Minuten verbunden. Wähle dein Gerät.",
        "chooseDevice": "Wähle dein Gerät",
        "android": {
            "title": "Android-Einrichtung",
            "subtitle": "Richte Doppler VPN auf deinem Android-Gerät ein",
            "step1Title": "V2RayNG herunterladen",
            "step1Desc": "Installiere V2RayNG aus dem Google Play Store oder lade die APK von GitHub herunter.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "VPN-Konfiguration abrufen",
            "step2Desc": "Öffne unseren Telegram-Bot @dopplercreatebot, tippe auf „Connect VPN", wähle einen Server und du erhältst einen VLESS-Konfigurationslink.",
            "step3Title": "Konfiguration importieren",
            "step3Desc": "Halte den VLESS-Link gedrückt, um ihn zu kopieren. Öffne V2RayNG → tippe auf das + → wähle „Import config from clipboard".",
            "step4Title": "Verbinden",
            "step4Desc": "Tippe auf den Play-Button, um dich zu verbinden. Erlaube die VPN-Berechtigung, wenn du dazu aufgefordert wirst. Du bist jetzt geschützt!",
            "troubleshootTitle": "Problemlösung",
            "troubleshoot1": "Falls die Verbindung fehlschlägt, probiere einen anderen Serverstandort im Bot.",
            "troubleshoot2": "Stelle sicher, dass die Akkuoptimierung für V2RayNG deaktiviert ist.",
            "troubleshoot3": "Für Hilfe schreibe @DopplerSupportBot auf Telegram – unser KI-Support ist rund um die Uhr verfügbar."
        },
        "ios": {
            "title": "iOS-Einrichtung",
            "subtitle": "Richte Doppler VPN auf deinem iPhone oder iPad ein",
            "step1Title": "Streisand herunterladen",
            "step1Desc": "Installiere Streisand aus dem App Store. Die App ist kostenlos und unterstützt das VLESS-Protokoll.",
            "step1AppStore": "App Store",
            "step2Title": "VPN-Konfiguration abrufen",
            "step2Desc": "Öffne unseren Telegram-Bot @dopplercreatebot, tippe auf „Connect VPN", wähle einen Server und du erhältst einen VLESS-Konfigurationslink.",
            "step3Title": "Konfiguration importieren",
            "step3Desc": "Halte den VLESS-Link gedrückt, um ihn zu kopieren. Öffne Streisand → tippe auf + → „Import from clipboard". Erlaube die VPN-Konfiguration, wenn du dazu aufgefordert wirst.",
            "step4Title": "Verbinden",
            "step4Desc": "Tippe auf den Schalter, um dich zu verbinden. Dein Datenverkehr ist jetzt verschlüsselt und geschützt!",
            "troubleshootTitle": "Problemlösung",
            "troubleshoot1": "Falls das VPN sich nicht verbindet, versuche die Konfiguration zu entfernen und neu zu importieren.",
            "troubleshoot2": "Stelle sicher, dass Streisand die Berechtigung hat, VPN-Konfigurationen hinzuzufügen unter Einstellungen > Allgemein > VPN.",
            "troubleshoot3": "Für Hilfe schreibe @DopplerSupportBot auf Telegram – unser KI-Support ist rund um die Uhr verfügbar."
        },
        "windows": {
            "title": "Windows-Einrichtung",
            "subtitle": "Richte Doppler VPN auf deinem Windows-PC ein",
            "step1Title": "v2rayN herunterladen",
            "step1Desc": "Lade v2rayN von GitHub herunter. Entpacke die ZIP-Datei und starte v2rayN.exe.",
            "step1Download": "v2rayN herunterladen",
            "step2Title": "VPN-Konfiguration abrufen",
            "step2Desc": "Öffne unseren Telegram-Bot @dopplercreatebot, tippe auf „Connect VPN", wähle einen Server und du erhältst einen VLESS-Konfigurationslink.",
            "step3Title": "Konfiguration importieren",
            "step3Desc": "Kopiere den VLESS-Link. Klicke in v2rayN auf „Server" → „Import from clipboard" oder drücke Strg+V.",
            "step4Title": "Verbinden",
            "step4Desc": "Klicke mit der rechten Maustaste auf das v2rayN-Symbol im Infobereich und wähle „System proxy" → „Set as system proxy". Du bist verbunden!",
            "troubleshootTitle": "Problemlösung",
            "troubleshoot1": "Stelle sicher, dass Windows Defender oder dein Antivirenprogramm v2rayN nicht blockiert.",
            "troubleshoot2": "Versuche, v2rayN als Administrator auszuführen.",
            "troubleshoot3": "Für Hilfe schreibe @DopplerSupportBot auf Telegram – unser KI-Support ist rund um die Uhr verfügbar."
        },
        "mac": {
            "title": "macOS-Einrichtung",
            "subtitle": "Richte Doppler VPN auf deinem Mac ein",
            "step1Title": "V2RayXS herunterladen",
            "step1Desc": "Lade V2RayXS von GitHub herunter oder installiere Streisand aus dem Mac App Store.",
            "step1Download": "V2RayXS herunterladen",
            "step1AppStore": "Mac App Store",
            "step2Title": "VPN-Konfiguration abrufen",
            "step2Desc": "Öffne unseren Telegram-Bot @dopplercreatebot, tippe auf „Connect VPN", wähle einen Server und du erhältst einen VLESS-Konfigurationslink.",
            "step3Title": "Konfiguration importieren",
            "step3Desc": "Kopiere den VLESS-Link. Öffne V2RayXS → „Import" → „From clipboard". Oder tippe in Streisand auf + → „Import from clipboard".",
            "step4Title": "Verbinden",
            "step4Desc": "Klicke auf Verbinden. Erlaube die VPN-Konfiguration, wenn macOS dich dazu auffordert. Fertig!",
            "troubleshootTitle": "Problemlösung",
            "troubleshoot1": "Falls macOS die App blockiert, gehe zu Systemeinstellungen > Datenschutz & Sicherheit und erlaube sie.",
            "troubleshoot2": "Versuche die App neu zu starten, wenn die Verbindung abbricht.",
            "troubleshoot3": "Für Hilfe schreibe @DopplerSupportBot auf Telegram – unser KI-Support ist rund um die Uhr verfügbar."
        },
        "telegramSection": {
            "title": "Telegram-Integration",
            "subtitle": "Erhalte deine VPN-Konfiguration und verwalte dein Abonnement direkt in Telegram.",
            "vpnBot": "VPN-Bot",
            "vpnBotDesc": "Erhalte deine VPN-Konfiguration, verbinde dich mit Servern und verwalte dein Konto.",
            "supportBot": "Support-Bot",
            "supportBotDesc": "KI-gestützter Support rund um die Uhr in 23 Sprachen. Sofortige Hilfe bei jedem Problem.",
            "miniApp": "Abo-Mini-App",
            "miniAppDesc": "Abonniere und verwalte deinen Plan über unsere Telegram-Mini-App mit sicherer Stripe-Zahlung."
        },
        "backToGuides": "Alle Anleitungen",
        "nextStep": "Weiter",
        "prevStep": "Zurück"
    },
    "es": {
        "title": "Guía de configuración",
        "subtitle": "Conéctate en minutos. Elige tu dispositivo para comenzar.",
        "chooseDevice": "Elige tu dispositivo",
        "android": {
            "title": "Configuración en Android",
            "subtitle": "Configura Doppler VPN en tu dispositivo Android",
            "step1Title": "Descarga V2RayNG",
            "step1Desc": "Instala V2RayNG desde Google Play Store o descarga el APK desde GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "Obtén tu configuración VPN",
            "step2Desc": "Abre nuestro bot de Telegram @dopplercreatebot, pulsa \"Connect VPN\", elige un servidor y recibirás un enlace de configuración VLESS.",
            "step3Title": "Importar configuración",
            "step3Desc": "Mantén pulsado el enlace VLESS para copiarlo. Abre V2RayNG → pulsa el botón + → selecciona \"Import config from clipboard\".",
            "step4Title": "Conectar",
            "step4Desc": "Pulsa el botón de reproducción para conectarte. Permite el permiso de VPN cuando se solicite. ¡Ya estás protegido!",
            "troubleshootTitle": "Solución de problemas",
            "troubleshoot1": "Si la conexión falla, prueba con otra ubicación de servidor en el bot.",
            "troubleshoot2": "Asegúrate de que la optimización de batería esté desactivada para V2RayNG.",
            "troubleshoot3": "Para obtener ayuda, escribe a @DopplerSupportBot en Telegram — nuestro soporte con IA está disponible 24/7."
        },
        "ios": {
            "title": "Configuración en iOS",
            "subtitle": "Configura Doppler VPN en tu iPhone o iPad",
            "step1Title": "Descarga Streisand",
            "step1Desc": "Instala Streisand desde la App Store. Es gratuita y compatible con el protocolo VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "Obtén tu configuración VPN",
            "step2Desc": "Abre nuestro bot de Telegram @dopplercreatebot, pulsa \"Connect VPN\", elige un servidor y recibirás un enlace de configuración VLESS.",
            "step3Title": "Importar configuración",
            "step3Desc": "Mantén pulsado el enlace VLESS para copiarlo. Abre Streisand → pulsa + → \"Import from clipboard\". Permite la configuración de VPN cuando se solicite.",
            "step4Title": "Conectar",
            "step4Desc": "Activa el interruptor para conectarte. ¡Tu tráfico ahora está cifrado y protegido!",
            "troubleshootTitle": "Solución de problemas",
            "troubleshoot1": "Si el VPN no se conecta, intenta eliminar y volver a importar la configuración.",
            "troubleshoot2": "Asegúrate de que Streisand tenga permiso para añadir configuraciones de VPN en Ajustes > General > VPN.",
            "troubleshoot3": "Para obtener ayuda, escribe a @DopplerSupportBot en Telegram — nuestro soporte con IA está disponible 24/7."
        },
        "windows": {
            "title": "Configuración en Windows",
            "subtitle": "Configura Doppler VPN en tu PC con Windows",
            "step1Title": "Descarga v2rayN",
            "step1Desc": "Descarga v2rayN desde GitHub. Extrae el archivo ZIP y ejecuta v2rayN.exe.",
            "step1Download": "Descargar v2rayN",
            "step2Title": "Obtén tu configuración VPN",
            "step2Desc": "Abre nuestro bot de Telegram @dopplercreatebot, pulsa \"Connect VPN\", elige un servidor y recibirás un enlace de configuración VLESS.",
            "step3Title": "Importar configuración",
            "step3Desc": "Copia el enlace VLESS. En v2rayN, haz clic en \"Server\" → \"Import from clipboard\" o pulsa Ctrl+V.",
            "step4Title": "Conectar",
            "step4Desc": "Haz clic derecho en el icono de v2rayN en la bandeja del sistema y selecciona \"System proxy\" → \"Set as system proxy\". ¡Ya estás conectado!",
            "troubleshootTitle": "Solución de problemas",
            "troubleshoot1": "Asegúrate de que Windows Defender o tu antivirus no estén bloqueando v2rayN.",
            "troubleshoot2": "Intenta ejecutar v2rayN como administrador.",
            "troubleshoot3": "Para obtener ayuda, escribe a @DopplerSupportBot en Telegram — nuestro soporte con IA está disponible 24/7."
        },
        "mac": {
            "title": "Configuración en macOS",
            "subtitle": "Configura Doppler VPN en tu Mac",
            "step1Title": "Descarga V2RayXS",
            "step1Desc": "Descarga V2RayXS desde GitHub o instala Streisand desde la Mac App Store.",
            "step1Download": "Descargar V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "Obtén tu configuración VPN",
            "step2Desc": "Abre nuestro bot de Telegram @dopplercreatebot, pulsa \"Connect VPN\", elige un servidor y recibirás un enlace de configuración VLESS.",
            "step3Title": "Importar configuración",
            "step3Desc": "Copia el enlace VLESS. Abre V2RayXS → \"Import\" → \"From clipboard\". O en Streisand, pulsa + → \"Import from clipboard\".",
            "step4Title": "Conectar",
            "step4Desc": "Haz clic en conectar. Permite la configuración de VPN cuando macOS te lo solicite. ¡Listo!",
            "troubleshootTitle": "Solución de problemas",
            "troubleshoot1": "Si macOS bloquea la aplicación, ve a Preferencias del Sistema > Privacidad y seguridad y permítela.",
            "troubleshoot2": "Intenta reiniciar la aplicación si la conexión se interrumpe.",
            "troubleshoot3": "Para obtener ayuda, escribe a @DopplerSupportBot en Telegram — nuestro soporte con IA está disponible 24/7."
        },
        "telegramSection": {
            "title": "Integración con Telegram",
            "subtitle": "Obtén tu configuración VPN y gestiona tu suscripción directamente en Telegram.",
            "vpnBot": "Bot de VPN",
            "vpnBotDesc": "Obtén tu configuración VPN, conéctate a servidores y gestiona tu cuenta.",
            "supportBot": "Bot de soporte",
            "supportBotDesc": "Soporte con IA disponible 24/7 en 23 idiomas. Ayuda instantánea con cualquier problema.",
            "miniApp": "Mini App de suscripción",
            "miniAppDesc": "Suscríbete y gestiona tu plan a través de nuestra Mini App de Telegram con pagos seguros de Stripe."
        },
        "backToGuides": "Todas las guías",
        "nextStep": "Siguiente",
        "prevStep": "Anterior"
    },
    "fr": {
        "title": "Guide d'installation",
        "subtitle": "Connectez-vous en quelques minutes. Choisissez votre appareil pour commencer.",
        "chooseDevice": "Choisissez votre appareil",
        "android": {
            "title": "Installation sur Android",
            "subtitle": "Configurez Doppler VPN sur votre appareil Android",
            "step1Title": "Télécharger V2RayNG",
            "step1Desc": "Installez V2RayNG depuis le Google Play Store ou téléchargez l'APK depuis GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "Obtenir votre configuration VPN",
            "step2Desc": "Ouvrez notre bot Telegram @dopplercreatebot, appuyez sur « Connect VPN », choisissez un serveur et vous recevrez un lien de configuration VLESS.",
            "step3Title": "Importer la configuration",
            "step3Desc": "Appuyez longuement sur le lien VLESS pour le copier. Ouvrez V2RayNG → appuyez sur le bouton + → sélectionnez « Import config from clipboard ».",
            "step4Title": "Se connecter",
            "step4Desc": "Appuyez sur le bouton lecture pour vous connecter. Autorisez la permission VPN lorsqu'elle est demandée. Vous êtes maintenant protégé !",
            "troubleshootTitle": "Dépannage",
            "troubleshoot1": "Si la connexion échoue, essayez un autre emplacement de serveur dans le bot.",
            "troubleshoot2": "Assurez-vous que l'optimisation de la batterie est désactivée pour V2RayNG.",
            "troubleshoot3": "Pour obtenir de l'aide, contactez @DopplerSupportBot sur Telegram — notre support IA est disponible 24h/24."
        },
        "ios": {
            "title": "Installation sur iOS",
            "subtitle": "Configurez Doppler VPN sur votre iPhone ou iPad",
            "step1Title": "Télécharger Streisand",
            "step1Desc": "Installez Streisand depuis l'App Store. L'application est gratuite et prend en charge le protocole VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "Obtenir votre configuration VPN",
            "step2Desc": "Ouvrez notre bot Telegram @dopplercreatebot, appuyez sur « Connect VPN », choisissez un serveur et vous recevrez un lien de configuration VLESS.",
            "step3Title": "Importer la configuration",
            "step3Desc": "Appuyez longuement sur le lien VLESS pour le copier. Ouvrez Streisand → appuyez sur + → « Import from clipboard ». Autorisez la configuration VPN lorsqu'elle est demandée.",
            "step4Title": "Se connecter",
            "step4Desc": "Activez l'interrupteur pour vous connecter. Votre trafic est maintenant chiffré et protégé !",
            "troubleshootTitle": "Dépannage",
            "troubleshoot1": "Si le VPN ne se connecte pas, essayez de supprimer et de réimporter la configuration.",
            "troubleshoot2": "Assurez-vous que Streisand a la permission d'ajouter des configurations VPN dans Réglages > Général > VPN.",
            "troubleshoot3": "Pour obtenir de l'aide, contactez @DopplerSupportBot sur Telegram — notre support IA est disponible 24h/24."
        },
        "windows": {
            "title": "Installation sur Windows",
            "subtitle": "Configurez Doppler VPN sur votre PC Windows",
            "step1Title": "Télécharger v2rayN",
            "step1Desc": "Téléchargez v2rayN depuis GitHub. Extrayez le fichier ZIP et lancez v2rayN.exe.",
            "step1Download": "Télécharger v2rayN",
            "step2Title": "Obtenir votre configuration VPN",
            "step2Desc": "Ouvrez notre bot Telegram @dopplercreatebot, appuyez sur « Connect VPN », choisissez un serveur et vous recevrez un lien de configuration VLESS.",
            "step3Title": "Importer la configuration",
            "step3Desc": "Copiez le lien VLESS. Dans v2rayN, cliquez sur « Server » → « Import from clipboard » ou appuyez sur Ctrl+V.",
            "step4Title": "Se connecter",
            "step4Desc": "Faites un clic droit sur l'icône v2rayN dans la barre des tâches et sélectionnez « System proxy » → « Set as system proxy ». Vous êtes connecté !",
            "troubleshootTitle": "Dépannage",
            "troubleshoot1": "Assurez-vous que Windows Defender ou votre antivirus ne bloque pas v2rayN.",
            "troubleshoot2": "Essayez d'exécuter v2rayN en tant qu'administrateur.",
            "troubleshoot3": "Pour obtenir de l'aide, contactez @DopplerSupportBot sur Telegram — notre support IA est disponible 24h/24."
        },
        "mac": {
            "title": "Installation sur macOS",
            "subtitle": "Configurez Doppler VPN sur votre Mac",
            "step1Title": "Télécharger V2RayXS",
            "step1Desc": "Téléchargez V2RayXS depuis GitHub ou installez Streisand depuis le Mac App Store.",
            "step1Download": "Télécharger V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "Obtenir votre configuration VPN",
            "step2Desc": "Ouvrez notre bot Telegram @dopplercreatebot, appuyez sur « Connect VPN », choisissez un serveur et vous recevrez un lien de configuration VLESS.",
            "step3Title": "Importer la configuration",
            "step3Desc": "Copiez le lien VLESS. Ouvrez V2RayXS → « Import » → « From clipboard ». Ou dans Streisand, appuyez sur + → « Import from clipboard ».",
            "step4Title": "Se connecter",
            "step4Desc": "Cliquez sur le bouton de connexion. Autorisez la configuration VPN lorsque macOS vous le demande. C'est fait !",
            "troubleshootTitle": "Dépannage",
            "troubleshoot1": "Si macOS bloque l'application, allez dans Préférences Système > Confidentialité et sécurité et autorisez-la.",
            "troubleshoot2": "Essayez de redémarrer l'application si la connexion est interrompue.",
            "troubleshoot3": "Pour obtenir de l'aide, contactez @DopplerSupportBot sur Telegram — notre support IA est disponible 24h/24."
        },
        "telegramSection": {
            "title": "Intégration Telegram",
            "subtitle": "Obtenez votre configuration VPN et gérez votre abonnement directement dans Telegram.",
            "vpnBot": "Bot VPN",
            "vpnBotDesc": "Obtenez votre configuration VPN, connectez-vous aux serveurs et gérez votre compte.",
            "supportBot": "Bot d'assistance",
            "supportBotDesc": "Assistance IA disponible 24h/24 en 23 langues. Aide instantanée pour tout problème.",
            "miniApp": "Mini App d'abonnement",
            "miniAppDesc": "Abonnez-vous et gérez votre forfait via notre Mini App Telegram avec des paiements Stripe sécurisés."
        },
        "backToGuides": "Tous les guides",
        "nextStep": "Suivant",
        "prevStep": "Précédent"
    },
    "pt": {
        "title": "Guia de configuração",
        "subtitle": "Conecte-se em minutos. Escolha seu dispositivo para começar.",
        "chooseDevice": "Escolha seu dispositivo",
        "android": {
            "title": "Configuração no Android",
            "subtitle": "Configure o Doppler VPN no seu dispositivo Android",
            "step1Title": "Baixar V2RayNG",
            "step1Desc": "Instale o V2RayNG pela Google Play Store ou baixe o APK pelo GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "Obter sua configuração VPN",
            "step2Desc": "Abra nosso bot do Telegram @dopplercreatebot, toque em \"Connect VPN\", escolha um servidor e você receberá um link de configuração VLESS.",
            "step3Title": "Importar configuração",
            "step3Desc": "Mantenha pressionado o link VLESS para copiá-lo. Abra o V2RayNG → toque no botão + → selecione \"Import config from clipboard\".",
            "step4Title": "Conectar",
            "step4Desc": "Toque no botão de reprodução para conectar. Permita a permissão de VPN quando solicitado. Agora você está protegido!",
            "troubleshootTitle": "Solução de problemas",
            "troubleshoot1": "Se a conexão falhar, tente outro servidor no bot.",
            "troubleshoot2": "Certifique-se de que a otimização de bateria esteja desativada para o V2RayNG.",
            "troubleshoot3": "Para ajuda, envie uma mensagem para @DopplerSupportBot no Telegram — nosso suporte com IA está disponível 24/7."
        },
        "ios": {
            "title": "Configuração no iOS",
            "subtitle": "Configure o Doppler VPN no seu iPhone ou iPad",
            "step1Title": "Baixar Streisand",
            "step1Desc": "Instale o Streisand pela App Store. É gratuito e suporta o protocolo VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "Obter sua configuração VPN",
            "step2Desc": "Abra nosso bot do Telegram @dopplercreatebot, toque em \"Connect VPN\", escolha um servidor e você receberá um link de configuração VLESS.",
            "step3Title": "Importar configuração",
            "step3Desc": "Mantenha pressionado o link VLESS para copiá-lo. Abra o Streisand → toque em + → \"Import from clipboard\". Permita a configuração de VPN quando solicitado.",
            "step4Title": "Conectar",
            "step4Desc": "Ative o interruptor para conectar. Seu tráfego agora está criptografado e protegido!",
            "troubleshootTitle": "Solução de problemas",
            "troubleshoot1": "Se o VPN não conectar, tente remover e reimportar a configuração.",
            "troubleshoot2": "Certifique-se de que o Streisand tem permissão para adicionar configurações de VPN em Ajustes > Geral > VPN.",
            "troubleshoot3": "Para ajuda, envie uma mensagem para @DopplerSupportBot no Telegram — nosso suporte com IA está disponível 24/7."
        },
        "windows": {
            "title": "Configuração no Windows",
            "subtitle": "Configure o Doppler VPN no seu PC Windows",
            "step1Title": "Baixar v2rayN",
            "step1Desc": "Baixe o v2rayN pelo GitHub. Extraia o arquivo ZIP e execute o v2rayN.exe.",
            "step1Download": "Baixar v2rayN",
            "step2Title": "Obter sua configuração VPN",
            "step2Desc": "Abra nosso bot do Telegram @dopplercreatebot, toque em \"Connect VPN\", escolha um servidor e você receberá um link de configuração VLESS.",
            "step3Title": "Importar configuração",
            "step3Desc": "Copie o link VLESS. No v2rayN, clique em \"Server\" → \"Import from clipboard\" ou pressione Ctrl+V.",
            "step4Title": "Conectar",
            "step4Desc": "Clique com o botão direito no ícone do v2rayN na bandeja do sistema e selecione \"System proxy\" → \"Set as system proxy\". Você está conectado!",
            "troubleshootTitle": "Solução de problemas",
            "troubleshoot1": "Certifique-se de que o Windows Defender ou seu antivírus não está bloqueando o v2rayN.",
            "troubleshoot2": "Tente executar o v2rayN como administrador.",
            "troubleshoot3": "Para ajuda, envie uma mensagem para @DopplerSupportBot no Telegram — nosso suporte com IA está disponível 24/7."
        },
        "mac": {
            "title": "Configuração no macOS",
            "subtitle": "Configure o Doppler VPN no seu Mac",
            "step1Title": "Baixar V2RayXS",
            "step1Desc": "Baixe o V2RayXS pelo GitHub ou instale o Streisand pela Mac App Store.",
            "step1Download": "Baixar V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "Obter sua configuração VPN",
            "step2Desc": "Abra nosso bot do Telegram @dopplercreatebot, toque em \"Connect VPN\", escolha um servidor e você receberá um link de configuração VLESS.",
            "step3Title": "Importar configuração",
            "step3Desc": "Copie o link VLESS. Abra o V2RayXS → \"Import\" → \"From clipboard\". Ou no Streisand, toque em + → \"Import from clipboard\".",
            "step4Title": "Conectar",
            "step4Desc": "Clique no botão de conexão. Permita a configuração de VPN quando o macOS solicitar. Pronto!",
            "troubleshootTitle": "Solução de problemas",
            "troubleshoot1": "Se o macOS bloquear o app, vá em Preferências do Sistema > Privacidade e Segurança e permita.",
            "troubleshoot2": "Tente reiniciar o app se a conexão cair.",
            "troubleshoot3": "Para ajuda, envie uma mensagem para @DopplerSupportBot no Telegram — nosso suporte com IA está disponível 24/7."
        },
        "telegramSection": {
            "title": "Integração com Telegram",
            "subtitle": "Obtenha sua configuração VPN e gerencie sua assinatura diretamente no Telegram.",
            "vpnBot": "Bot de VPN",
            "vpnBotDesc": "Obtenha sua configuração VPN, conecte-se a servidores e gerencie sua conta.",
            "supportBot": "Bot de suporte",
            "supportBotDesc": "Suporte com IA 24/7 em 23 idiomas. Ajuda instantânea para qualquer problema.",
            "miniApp": "Mini App de assinatura",
            "miniAppDesc": "Assine e gerencie seu plano pelo nosso Mini App do Telegram com pagamentos seguros via Stripe."
        },
        "backToGuides": "Todos os guias",
        "nextStep": "Próximo",
        "prevStep": "Anterior"
    },
    "ja": {
        "title": "セットアップガイド",
        "subtitle": "数分で接続できます。デバイスを選んで始めましょう。",
        "chooseDevice": "デバイスを選択",
        "android": {
            "title": "Androidセットアップ",
            "subtitle": "AndroidデバイスでDoppler VPNを設定する",
            "step1Title": "V2RayNGをダウンロード",
            "step1Desc": "Google Play StoreからV2RayNGをインストールするか、GitHubからAPKをダウンロードしてください。",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "VPN設定を取得",
            "step2Desc": "Telegramボット @dopplercreatebot を開き、「Connect VPN」をタップしてサーバーを選択すると、VLESS設定リンクが届きます。",
            "step3Title": "設定をインポート",
            "step3Desc": "VLESSリンクを長押ししてコピーします。V2RayNGを開き → +ボタンをタップ → 「Import config from clipboard」を選択してください。",
            "step4Title": "接続",
            "step4Desc": "再生ボタンをタップして接続します。VPN許可を求められたら許可してください。これで保護されています！",
            "troubleshootTitle": "トラブルシューティング",
            "troubleshoot1": "接続に失敗した場合は、ボットで別のサーバーを試してください。",
            "troubleshoot2": "V2RayNGのバッテリー最適化が無効になっていることを確認してください。",
            "troubleshoot3": "ヘルプが必要な場合は、Telegramで @DopplerSupportBot にメッセージを送ってください。AIサポートが24時間対応しています。"
        },
        "ios": {
            "title": "iOSセットアップ",
            "subtitle": "iPhoneまたはiPadでDoppler VPNを設定する",
            "step1Title": "Streisandをダウンロード",
            "step1Desc": "App StoreからStreisandをインストールしてください。無料でVLESSプロトコルに対応しています。",
            "step1AppStore": "App Store",
            "step2Title": "VPN設定を取得",
            "step2Desc": "Telegramボット @dopplercreatebot を開き、「Connect VPN」をタップしてサーバーを選択すると、VLESS設定リンクが届きます。",
            "step3Title": "設定をインポート",
            "step3Desc": "VLESSリンクを長押ししてコピーします。Streisandを開き → +をタップ → 「Import from clipboard」を選択。VPN構成を求められたら許可してください。",
            "step4Title": "接続",
            "step4Desc": "スイッチをタップして接続します。通信が暗号化され保護されます！",
            "troubleshootTitle": "トラブルシューティング",
            "troubleshoot1": "VPNが接続できない場合は、設定を削除して再インポートしてみてください。",
            "troubleshoot2": "設定 > 一般 > VPN でStreisandにVPN構成の追加が許可されていることを確認してください。",
            "troubleshoot3": "ヘルプが必要な場合は、Telegramで @DopplerSupportBot にメッセージを送ってください。AIサポートが24時間対応しています。"
        },
        "windows": {
            "title": "Windowsセットアップ",
            "subtitle": "Windows PCでDoppler VPNを設定する",
            "step1Title": "v2rayNをダウンロード",
            "step1Desc": "GitHubからv2rayNをダウンロードしてください。ZIPファイルを展開し、v2rayN.exeを実行します。",
            "step1Download": "v2rayNをダウンロード",
            "step2Title": "VPN設定を取得",
            "step2Desc": "Telegramボット @dopplercreatebot を開き、「Connect VPN」をタップしてサーバーを選択すると、VLESS設定リンクが届きます。",
            "step3Title": "設定をインポート",
            "step3Desc": "VLESSリンクをコピーします。v2rayNで「Server」→「Import from clipboard」をクリックするか、Ctrl+Vを押してください。",
            "step4Title": "接続",
            "step4Desc": "v2rayNのタスクトレイアイコンを右クリックし、「System proxy」→「Set as system proxy」を選択してください。接続完了です！",
            "troubleshootTitle": "トラブルシューティング",
            "troubleshoot1": "Windows Defenderやアンチウイルスソフトがv2rayNをブロックしていないか確認してください。",
            "troubleshoot2": "v2rayNを管理者として実行してみてください。",
            "troubleshoot3": "ヘルプが必要な場合は、Telegramで @DopplerSupportBot にメッセージを送ってください。AIサポートが24時間対応しています。"
        },
        "mac": {
            "title": "macOSセットアップ",
            "subtitle": "MacでDoppler VPNを設定する",
            "step1Title": "V2RayXSをダウンロード",
            "step1Desc": "GitHubからV2RayXSをダウンロードするか、Mac App StoreからStreisandをインストールしてください。",
            "step1Download": "V2RayXSをダウンロード",
            "step1AppStore": "Mac App Store",
            "step2Title": "VPN設定を取得",
            "step2Desc": "Telegramボット @dopplercreatebot を開き、「Connect VPN」をタップしてサーバーを選択すると、VLESS設定リンクが届きます。",
            "step3Title": "設定をインポート",
            "step3Desc": "VLESSリンクをコピーします。V2RayXSを開き →「Import」→「From clipboard」。またはStreisandで +をタップ →「Import from clipboard」。",
            "step4Title": "接続",
            "step4Desc": "接続ボタンをクリックします。macOSが求めたらVPN構成を許可してください。完了です！",
            "troubleshootTitle": "トラブルシューティング",
            "troubleshoot1": "macOSがアプリをブロックする場合は、システム環境設定 > プライバシーとセキュリティで許可してください。",
            "troubleshoot2": "接続が切れた場合はアプリを再起動してみてください。",
            "troubleshoot3": "ヘルプが必要な場合は、Telegramで @DopplerSupportBot にメッセージを送ってください。AIサポートが24時間対応しています。"
        },
        "telegramSection": {
            "title": "Telegram連携",
            "subtitle": "Telegramで直接VPN設定を取得し、サブスクリプションを管理できます。",
            "vpnBot": "VPNボット",
            "vpnBotDesc": "VPN設定の取得、サーバーへの接続、アカウント管理ができます。",
            "supportBot": "サポートボット",
            "supportBotDesc": "23言語対応のAIサポートが24時間利用可能。あらゆる問題に即座に対応します。",
            "miniApp": "サブスクリプション Mini App",
            "miniAppDesc": "Telegram Mini Appで安全なStripe決済によるプランの登録・管理ができます。"
        },
        "backToGuides": "全ガイド",
        "nextStep": "次へ",
        "prevStep": "前へ"
    },
    "ko": {
        "title": "설정 가이드",
        "subtitle": "몇 분 안에 연결하세요. 기기를 선택하여 시작합니다.",
        "chooseDevice": "기기 선택",
        "android": {
            "title": "Android 설정",
            "subtitle": "Android 기기에서 Doppler VPN 설정하기",
            "step1Title": "V2RayNG 다운로드",
            "step1Desc": "Google Play Store에서 V2RayNG를 설치하거나 GitHub에서 APK를 다운로드하세요.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "VPN 설정 받기",
            "step2Desc": "Telegram 봇 @dopplercreatebot 을 열고 \"Connect VPN\"을 탭하고 서버를 선택하면 VLESS 설정 링크를 받게 됩니다.",
            "step3Title": "설정 가져오기",
            "step3Desc": "VLESS 링크를 길게 눌러 복사하세요. V2RayNG를 열고 → + 버튼 탭 → \"Import config from clipboard\"를 선택하세요.",
            "step4Title": "연결",
            "step4Desc": "재생 버튼을 탭하여 연결하세요. VPN 권한을 요청하면 허용하세요. 이제 보호되고 있습니다!",
            "troubleshootTitle": "문제 해결",
            "troubleshoot1": "연결에 실패하면 봇에서 다른 서버 위치를 시도해 보세요.",
            "troubleshoot2": "V2RayNG의 배터리 최적화가 비활성화되어 있는지 확인하세요.",
            "troubleshoot3": "도움이 필요하면 Telegram에서 @DopplerSupportBot 에 메시지를 보내세요 — AI 지원이 24시간 제공됩니다."
        },
        "ios": {
            "title": "iOS 설정",
            "subtitle": "iPhone 또는 iPad에서 Doppler VPN 설정하기",
            "step1Title": "Streisand 다운로드",
            "step1Desc": "App Store에서 Streisand를 설치하세요. 무료이며 VLESS 프로토콜을 지원합니다.",
            "step1AppStore": "App Store",
            "step2Title": "VPN 설정 받기",
            "step2Desc": "Telegram 봇 @dopplercreatebot 을 열고 \"Connect VPN\"을 탭하고 서버를 선택하면 VLESS 설정 링크를 받게 됩니다.",
            "step3Title": "설정 가져오기",
            "step3Desc": "VLESS 링크를 길게 눌러 복사하세요. Streisand를 열고 → + 탭 → \"Import from clipboard\"를 선택하세요. VPN 구성을 요청하면 허용하세요.",
            "step4Title": "연결",
            "step4Desc": "토글을 탭하여 연결하세요. 이제 트래픽이 암호화되어 보호됩니다!",
            "troubleshootTitle": "문제 해결",
            "troubleshoot1": "VPN이 연결되지 않으면 설정을 삭제하고 다시 가져와 보세요.",
            "troubleshoot2": "설정 > 일반 > VPN에서 Streisand에 VPN 구성 추가 권한이 있는지 확인하세요.",
            "troubleshoot3": "도움이 필요하면 Telegram에서 @DopplerSupportBot 에 메시지를 보내세요 — AI 지원이 24시간 제공됩니다."
        },
        "windows": {
            "title": "Windows 설정",
            "subtitle": "Windows PC에서 Doppler VPN 설정하기",
            "step1Title": "v2rayN 다운로드",
            "step1Desc": "GitHub에서 v2rayN을 다운로드하세요. ZIP 파일을 압축 해제하고 v2rayN.exe를 실행하세요.",
            "step1Download": "v2rayN 다운로드",
            "step2Title": "VPN 설정 받기",
            "step2Desc": "Telegram 봇 @dopplercreatebot 을 열고 \"Connect VPN\"을 탭하고 서버를 선택하면 VLESS 설정 링크를 받게 됩니다.",
            "step3Title": "설정 가져오기",
            "step3Desc": "VLESS 링크를 복사하세요. v2rayN에서 \"Server\" → \"Import from clipboard\"를 클릭하거나 Ctrl+V를 누르세요.",
            "step4Title": "연결",
            "step4Desc": "v2rayN 트레이 아이콘을 우클릭하고 \"System proxy\" → \"Set as system proxy\"를 선택하세요. 연결 완료!",
            "troubleshootTitle": "문제 해결",
            "troubleshoot1": "Windows Defender나 바이러스 백신이 v2rayN을 차단하고 있지 않은지 확인하세요.",
            "troubleshoot2": "v2rayN을 관리자로 실행해 보세요.",
            "troubleshoot3": "도움이 필요하면 Telegram에서 @DopplerSupportBot 에 메시지를 보내세요 — AI 지원이 24시간 제공됩니다."
        },
        "mac": {
            "title": "macOS 설정",
            "subtitle": "Mac에서 Doppler VPN 설정하기",
            "step1Title": "V2RayXS 다운로드",
            "step1Desc": "GitHub에서 V2RayXS를 다운로드하거나 Mac App Store에서 Streisand를 설치하세요.",
            "step1Download": "V2RayXS 다운로드",
            "step1AppStore": "Mac App Store",
            "step2Title": "VPN 설정 받기",
            "step2Desc": "Telegram 봇 @dopplercreatebot 을 열고 \"Connect VPN\"을 탭하고 서버를 선택하면 VLESS 설정 링크를 받게 됩니다.",
            "step3Title": "설정 가져오기",
            "step3Desc": "VLESS 링크를 복사하세요. V2RayXS를 열고 → \"Import\" → \"From clipboard\"를 선택하세요. 또는 Streisand에서 + 탭 → \"Import from clipboard\".",
            "step4Title": "연결",
            "step4Desc": "연결 버튼을 클릭하세요. macOS에서 VPN 구성을 요청하면 허용하세요. 완료!",
            "troubleshootTitle": "문제 해결",
            "troubleshoot1": "macOS가 앱을 차단하면 시스템 환경설정 > 개인 정보 보호 및 보안에서 허용하세요.",
            "troubleshoot2": "연결이 끊기면 앱을 다시 시작해 보세요.",
            "troubleshoot3": "도움이 필요하면 Telegram에서 @DopplerSupportBot 에 메시지를 보내세요 — AI 지원이 24시간 제공됩니다."
        },
        "telegramSection": {
            "title": "Telegram 연동",
            "subtitle": "Telegram에서 직접 VPN 설정을 받고 구독을 관리하세요.",
            "vpnBot": "VPN 봇",
            "vpnBotDesc": "VPN 설정을 받고 서버에 연결하고 계정을 관리하세요.",
            "supportBot": "지원 봇",
            "supportBotDesc": "23개 언어로 24시간 AI 지원. 모든 문제에 즉각적인 도움을 제공합니다.",
            "miniApp": "구독 Mini App",
            "miniAppDesc": "Telegram Mini App에서 안전한 Stripe 결제로 요금제를 구독하고 관리하세요."
        },
        "backToGuides": "전체 가이드",
        "nextStep": "다음",
        "prevStep": "이전"
    },
    "ar": {
        "title": "دليل الإعداد",
        "subtitle": "اتصل في دقائق. اختر جهازك للبدء.",
        "chooseDevice": "اختر جهازك",
        "android": {
            "title": "إعداد Android",
            "subtitle": "قم بإعداد Doppler VPN على جهاز Android الخاص بك",
            "step1Title": "تنزيل V2RayNG",
            "step1Desc": "ثبّت V2RayNG من Google Play Store أو حمّل ملف APK من GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "احصل على إعدادات VPN",
            "step2Desc": "افتح بوت Telegram الخاص بنا @dopplercreatebot، اضغط على \"Connect VPN\"، اختر خادمًا وستحصل على رابط إعدادات VLESS.",
            "step3Title": "استيراد الإعدادات",
            "step3Desc": "اضغط مطولاً على رابط VLESS لنسخه. افتح V2RayNG ← اضغط على زر + ← اختر \"Import config from clipboard\".",
            "step4Title": "الاتصال",
            "step4Desc": "اضغط على زر التشغيل للاتصال. اسمح بإذن VPN عند الطلب. أنت الآن محمي!",
            "troubleshootTitle": "استكشاف الأخطاء",
            "troubleshoot1": "إذا فشل الاتصال، جرّب موقع خادم مختلف في البوت.",
            "troubleshoot2": "تأكد من تعطيل تحسين البطارية لـ V2RayNG.",
            "troubleshoot3": "للمساعدة، أرسل رسالة إلى @DopplerSupportBot على Telegram — دعمنا بالذكاء الاصطناعي متاح على مدار الساعة."
        },
        "ios": {
            "title": "إعداد iOS",
            "subtitle": "قم بإعداد Doppler VPN على iPhone أو iPad",
            "step1Title": "تنزيل Streisand",
            "step1Desc": "ثبّت Streisand من App Store. التطبيق مجاني ويدعم بروتوكول VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "احصل على إعدادات VPN",
            "step2Desc": "افتح بوت Telegram الخاص بنا @dopplercreatebot، اضغط على \"Connect VPN\"، اختر خادمًا وستحصل على رابط إعدادات VLESS.",
            "step3Title": "استيراد الإعدادات",
            "step3Desc": "اضغط مطولاً على رابط VLESS لنسخه. افتح Streisand ← اضغط + ← \"Import from clipboard\". اسمح بتكوين VPN عند الطلب.",
            "step4Title": "الاتصال",
            "step4Desc": "اضغط على المفتاح للاتصال. حركة المرور الخاصة بك الآن مشفرة ومحمية!",
            "troubleshootTitle": "استكشاف الأخطاء",
            "troubleshoot1": "إذا لم يتصل VPN، جرّب حذف الإعدادات وإعادة استيرادها.",
            "troubleshoot2": "تأكد من أن Streisand لديه إذن لإضافة تكوينات VPN في الإعدادات > عام > VPN.",
            "troubleshoot3": "للمساعدة، أرسل رسالة إلى @DopplerSupportBot على Telegram — دعمنا بالذكاء الاصطناعي متاح على مدار الساعة."
        },
        "windows": {
            "title": "إعداد Windows",
            "subtitle": "قم بإعداد Doppler VPN على جهاز الكمبيوتر بنظام Windows",
            "step1Title": "تنزيل v2rayN",
            "step1Desc": "حمّل v2rayN من GitHub. فك ضغط ملف ZIP وشغّل v2rayN.exe.",
            "step1Download": "تنزيل v2rayN",
            "step2Title": "احصل على إعدادات VPN",
            "step2Desc": "افتح بوت Telegram الخاص بنا @dopplercreatebot، اضغط على \"Connect VPN\"، اختر خادمًا وستحصل على رابط إعدادات VLESS.",
            "step3Title": "استيراد الإعدادات",
            "step3Desc": "انسخ رابط VLESS. في v2rayN، انقر على \"Server\" ← \"Import from clipboard\" أو اضغط Ctrl+V.",
            "step4Title": "الاتصال",
            "step4Desc": "انقر بزر الماوس الأيمن على أيقونة v2rayN في شريط المهام واختر \"System proxy\" ← \"Set as system proxy\". أنت متصل الآن!",
            "troubleshootTitle": "استكشاف الأخطاء",
            "troubleshoot1": "تأكد من أن Windows Defender أو مضاد الفيروسات لا يحظر v2rayN.",
            "troubleshoot2": "جرّب تشغيل v2rayN كمسؤول.",
            "troubleshoot3": "للمساعدة، أرسل رسالة إلى @DopplerSupportBot على Telegram — دعمنا بالذكاء الاصطناعي متاح على مدار الساعة."
        },
        "mac": {
            "title": "إعداد macOS",
            "subtitle": "قم بإعداد Doppler VPN على جهاز Mac",
            "step1Title": "تنزيل V2RayXS",
            "step1Desc": "حمّل V2RayXS من GitHub أو ثبّت Streisand من Mac App Store.",
            "step1Download": "تنزيل V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "احصل على إعدادات VPN",
            "step2Desc": "افتح بوت Telegram الخاص بنا @dopplercreatebot، اضغط على \"Connect VPN\"، اختر خادمًا وستحصل على رابط إعدادات VLESS.",
            "step3Title": "استيراد الإعدادات",
            "step3Desc": "انسخ رابط VLESS. افتح V2RayXS ← \"Import\" ← \"From clipboard\". أو في Streisand، اضغط + ← \"Import from clipboard\".",
            "step4Title": "الاتصال",
            "step4Desc": "انقر على زر الاتصال. اسمح بتكوين VPN عندما يطلب macOS ذلك. تم!",
            "troubleshootTitle": "استكشاف الأخطاء",
            "troubleshoot1": "إذا حظر macOS التطبيق، انتقل إلى تفضيلات النظام > الخصوصية والأمان واسمح به.",
            "troubleshoot2": "جرّب إعادة تشغيل التطبيق إذا انقطع الاتصال.",
            "troubleshoot3": "للمساعدة، أرسل رسالة إلى @DopplerSupportBot على Telegram — دعمنا بالذكاء الاصطناعي متاح على مدار الساعة."
        },
        "telegramSection": {
            "title": "تكامل Telegram",
            "subtitle": "احصل على إعدادات VPN وأدر اشتراكك مباشرة في Telegram.",
            "vpnBot": "بوت VPN",
            "vpnBotDesc": "احصل على إعدادات VPN واتصل بالخوادم وأدر حسابك.",
            "supportBot": "بوت الدعم",
            "supportBotDesc": "دعم بالذكاء الاصطناعي على مدار الساعة بـ 23 لغة. مساعدة فورية لأي مشكلة.",
            "miniApp": "تطبيق الاشتراك المصغر",
            "miniAppDesc": "اشترك وأدر خطتك عبر تطبيق Telegram المصغر مع مدفوعات Stripe الآمنة."
        },
        "backToGuides": "جميع الأدلة",
        "nextStep": "التالي",
        "prevStep": "السابق"
    },
    "fa": {
        "title": "راهنمای راه‌اندازی",
        "subtitle": "در چند دقیقه متصل شوید. دستگاه خود را انتخاب کنید.",
        "chooseDevice": "دستگاه خود را انتخاب کنید",
        "android": {
            "title": "راه‌اندازی Android",
            "subtitle": "Doppler VPN را روی دستگاه Android خود تنظیم کنید",
            "step1Title": "دانلود V2RayNG",
            "step1Desc": "V2RayNG را از Google Play Store نصب کنید یا فایل APK را از GitHub دانلود کنید.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "دریافت تنظیمات VPN",
            "step2Desc": "ربات تلگرام ما @dopplercreatebot را باز کنید، روی \"Connect VPN\" بزنید، یک سرور انتخاب کنید و لینک تنظیمات VLESS را دریافت خواهید کرد.",
            "step3Title": "وارد کردن تنظیمات",
            "step3Desc": "روی لینک VLESS نگه دارید تا کپی شود. V2RayNG را باز کنید ← روی دکمه + بزنید ← \"Import config from clipboard\" را انتخاب کنید.",
            "step4Title": "اتصال",
            "step4Desc": "روی دکمه پخش بزنید تا متصل شوید. هنگام درخواست، مجوز VPN را بدهید. اکنون محافظت می‌شوید!",
            "troubleshootTitle": "عیب‌یابی",
            "troubleshoot1": "اگر اتصال ناموفق بود، مکان سرور دیگری را در ربات امتحان کنید.",
            "troubleshoot2": "مطمئن شوید بهینه‌سازی باتری برای V2RayNG غیرفعال است.",
            "troubleshoot3": "برای کمک، به @DopplerSupportBot در تلگرام پیام دهید — پشتیبانی هوش مصنوعی ما ۲۴ ساعته در دسترس است."
        },
        "ios": {
            "title": "راه‌اندازی iOS",
            "subtitle": "Doppler VPN را روی iPhone یا iPad خود تنظیم کنید",
            "step1Title": "دانلود Streisand",
            "step1Desc": "Streisand را از App Store نصب کنید. رایگان است و از پروتکل VLESS پشتیبانی می‌کند.",
            "step1AppStore": "App Store",
            "step2Title": "دریافت تنظیمات VPN",
            "step2Desc": "ربات تلگرام ما @dopplercreatebot را باز کنید، روی \"Connect VPN\" بزنید، یک سرور انتخاب کنید و لینک تنظیمات VLESS را دریافت خواهید کرد.",
            "step3Title": "وارد کردن تنظیمات",
            "step3Desc": "روی لینک VLESS نگه دارید تا کپی شود. Streisand را باز کنید ← روی + بزنید ← \"Import from clipboard\". هنگام درخواست، پیکربندی VPN را اجازه دهید.",
            "step4Title": "اتصال",
            "step4Desc": "روی کلید بزنید تا متصل شوید. ترافیک شما اکنون رمزنگاری و محافظت می‌شود!",
            "troubleshootTitle": "عیب‌یابی",
            "troubleshoot1": "اگر VPN متصل نمی‌شود، تنظیمات را حذف و دوباره وارد کنید.",
            "troubleshoot2": "مطمئن شوید Streisand مجوز افزودن پیکربندی VPN را دارد: تنظیمات > عمومی > VPN.",
            "troubleshoot3": "برای کمک، به @DopplerSupportBot در تلگرام پیام دهید — پشتیبانی هوش مصنوعی ما ۲۴ ساعته در دسترس است."
        },
        "windows": {
            "title": "راه‌اندازی Windows",
            "subtitle": "Doppler VPN را روی کامپیوتر Windows خود تنظیم کنید",
            "step1Title": "دانلود v2rayN",
            "step1Desc": "v2rayN را از GitHub دانلود کنید. فایل ZIP را استخراج کرده و v2rayN.exe را اجرا کنید.",
            "step1Download": "دانلود v2rayN",
            "step2Title": "دریافت تنظیمات VPN",
            "step2Desc": "ربات تلگرام ما @dopplercreatebot را باز کنید، روی \"Connect VPN\" بزنید، یک سرور انتخاب کنید و لینک تنظیمات VLESS را دریافت خواهید کرد.",
            "step3Title": "وارد کردن تنظیمات",
            "step3Desc": "لینک VLESS را کپی کنید. در v2rayN، روی \"Server\" ← \"Import from clipboard\" کلیک کنید یا Ctrl+V بزنید.",
            "step4Title": "اتصال",
            "step4Desc": "روی آیکون v2rayN در نوار وظیفه راست‌کلیک کنید و \"System proxy\" ← \"Set as system proxy\" را انتخاب کنید. متصل شدید!",
            "troubleshootTitle": "عیب‌یابی",
            "troubleshoot1": "مطمئن شوید Windows Defender یا آنتی‌ویروس شما v2rayN را مسدود نکرده باشد.",
            "troubleshoot2": "v2rayN را به عنوان مدیر اجرا کنید.",
            "troubleshoot3": "برای کمک، به @DopplerSupportBot در تلگرام پیام دهید — پشتیبانی هوش مصنوعی ما ۲۴ ساعته در دسترس است."
        },
        "mac": {
            "title": "راه‌اندازی macOS",
            "subtitle": "Doppler VPN را روی Mac خود تنظیم کنید",
            "step1Title": "دانلود V2RayXS",
            "step1Desc": "V2RayXS را از GitHub دانلود کنید یا Streisand را از Mac App Store نصب کنید.",
            "step1Download": "دانلود V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "دریافت تنظیمات VPN",
            "step2Desc": "ربات تلگرام ما @dopplercreatebot را باز کنید، روی \"Connect VPN\" بزنید، یک سرور انتخاب کنید و لینک تنظیمات VLESS را دریافت خواهید کرد.",
            "step3Title": "وارد کردن تنظیمات",
            "step3Desc": "لینک VLESS را کپی کنید. V2RayXS را باز کنید ← \"Import\" ← \"From clipboard\". یا در Streisand، روی + بزنید ← \"Import from clipboard\".",
            "step4Title": "اتصال",
            "step4Desc": "روی دکمه اتصال کلیک کنید. هنگام درخواست macOS، پیکربندی VPN را اجازه دهید. تمام!",
            "troubleshootTitle": "عیب‌یابی",
            "troubleshoot1": "اگر macOS برنامه را مسدود کرد، به تنظیمات سیستم > حریم خصوصی و امنیت بروید و اجازه دهید.",
            "troubleshoot2": "اگر اتصال قطع شد، برنامه را دوباره راه‌اندازی کنید.",
            "troubleshoot3": "برای کمک، به @DopplerSupportBot در تلگرام پیام دهید — پشتیبانی هوش مصنوعی ما ۲۴ ساعته در دسترس است."
        },
        "telegramSection": {
            "title": "ادغام با تلگرام",
            "subtitle": "تنظیمات VPN خود را دریافت کنید و اشتراک خود را مستقیماً در تلگرام مدیریت کنید.",
            "vpnBot": "ربات VPN",
            "vpnBotDesc": "تنظیمات VPN را دریافت کنید، به سرورها متصل شوید و حساب خود را مدیریت کنید.",
            "supportBot": "ربات پشتیبانی",
            "supportBotDesc": "پشتیبانی هوش مصنوعی ۲۴ ساعته به ۲۳ زبان. کمک فوری برای هر مشکلی.",
            "miniApp": "مینی اپ اشتراک",
            "miniAppDesc": "از طریق مینی اپ تلگرام ما با پرداخت امن Stripe اشتراک بگیرید و پلن خود را مدیریت کنید."
        },
        "backToGuides": "همه راهنماها",
        "nextStep": "بعدی",
        "prevStep": "قبلی"
    },
    "he": {
        "title": "מדריך התקנה",
        "subtitle": "התחברו תוך דקות. בחרו את המכשיר שלכם כדי להתחיל.",
        "chooseDevice": "בחרו את המכשיר שלכם",
        "android": {
            "title": "התקנה ב-Android",
            "subtitle": "הגדירו את Doppler VPN במכשיר Android שלכם",
            "step1Title": "הורדת V2RayNG",
            "step1Desc": "התקינו את V2RayNG מ-Google Play Store או הורידו את ה-APK מ-GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "קבלת הגדרות VPN",
            "step2Desc": "פתחו את הבוט שלנו בטלגרם @dopplercreatebot, לחצו על \"Connect VPN\", בחרו שרת ותקבלו קישור להגדרות VLESS.",
            "step3Title": "ייבוא הגדרות",
            "step3Desc": "לחצו ארוך על קישור VLESS כדי להעתיקו. פתחו את V2RayNG ← לחצו על + ← בחרו \"Import config from clipboard\".",
            "step4Title": "התחברות",
            "step4Desc": "לחצו על כפתור ההפעלה כדי להתחבר. אשרו את הרשאת VPN כשתתבקשו. אתם מוגנים עכשיו!",
            "troubleshootTitle": "פתרון בעיות",
            "troubleshoot1": "אם החיבור נכשל, נסו מיקום שרת אחר בבוט.",
            "troubleshoot2": "ודאו שאופטימיזציית הסוללה מושבתת עבור V2RayNG.",
            "troubleshoot3": "לעזרה, שלחו הודעה ל-@DopplerSupportBot בטלגרם — התמיכה שלנו בבינה מלאכותית זמינה 24/7."
        },
        "ios": {
            "title": "התקנה ב-iOS",
            "subtitle": "הגדירו את Doppler VPN ב-iPhone או iPad שלכם",
            "step1Title": "הורדת Streisand",
            "step1Desc": "התקינו את Streisand מ-App Store. האפליקציה חינמית ותומכת בפרוטוקול VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "קבלת הגדרות VPN",
            "step2Desc": "פתחו את הבוט שלנו בטלגרם @dopplercreatebot, לחצו על \"Connect VPN\", בחרו שרת ותקבלו קישור להגדרות VLESS.",
            "step3Title": "ייבוא הגדרות",
            "step3Desc": "לחצו ארוך על קישור VLESS כדי להעתיקו. פתחו את Streisand ← לחצו + ← \"Import from clipboard\". אשרו את הגדרת VPN כשתתבקשו.",
            "step4Title": "התחברות",
            "step4Desc": "הפעילו את המתג כדי להתחבר. התעבורה שלכם מוצפנת ומוגנת עכשיו!",
            "troubleshootTitle": "פתרון בעיות",
            "troubleshoot1": "אם ה-VPN לא מתחבר, נסו למחוק ולייבא מחדש את ההגדרות.",
            "troubleshoot2": "ודאו ש-Streisand מורשה להוסיף הגדרות VPN בהגדרות > כללי > VPN.",
            "troubleshoot3": "לעזרה, שלחו הודעה ל-@DopplerSupportBot בטלגרם — התמיכה שלנו בבינה מלאכותית זמינה 24/7."
        },
        "windows": {
            "title": "התקנה ב-Windows",
            "subtitle": "הגדירו את Doppler VPN במחשב Windows שלכם",
            "step1Title": "הורדת v2rayN",
            "step1Desc": "הורידו את v2rayN מ-GitHub. חלצו את קובץ ZIP והפעילו את v2rayN.exe.",
            "step1Download": "הורדת v2rayN",
            "step2Title": "קבלת הגדרות VPN",
            "step2Desc": "פתחו את הבוט שלנו בטלגרם @dopplercreatebot, לחצו על \"Connect VPN\", בחרו שרת ותקבלו קישור להגדרות VLESS.",
            "step3Title": "ייבוא הגדרות",
            "step3Desc": "העתיקו את קישור VLESS. ב-v2rayN, לחצו על \"Server\" ← \"Import from clipboard\" או Ctrl+V.",
            "step4Title": "התחברות",
            "step4Desc": "לחצו ימני על סמל v2rayN במגש המערכת ובחרו \"System proxy\" ← \"Set as system proxy\". אתם מחוברים!",
            "troubleshootTitle": "פתרון בעיות",
            "troubleshoot1": "ודאו ש-Windows Defender או האנטי-וירוס שלכם לא חוסמים את v2rayN.",
            "troubleshoot2": "נסו להפעיל את v2rayN כמנהל מערכת.",
            "troubleshoot3": "לעזרה, שלחו הודעה ל-@DopplerSupportBot בטלגרם — התמיכה שלנו בבינה מלאכותית זמינה 24/7."
        },
        "mac": {
            "title": "התקנה ב-macOS",
            "subtitle": "הגדירו את Doppler VPN ב-Mac שלכם",
            "step1Title": "הורדת V2RayXS",
            "step1Desc": "הורידו את V2RayXS מ-GitHub או התקינו את Streisand מ-Mac App Store.",
            "step1Download": "הורדת V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "קבלת הגדרות VPN",
            "step2Desc": "פתחו את הבוט שלנו בטלגרם @dopplercreatebot, לחצו על \"Connect VPN\", בחרו שרת ותקבלו קישור להגדרות VLESS.",
            "step3Title": "ייבוא הגדרות",
            "step3Desc": "העתיקו את קישור VLESS. פתחו V2RayXS ← \"Import\" ← \"From clipboard\". או ב-Streisand, לחצו + ← \"Import from clipboard\".",
            "step4Title": "התחברות",
            "step4Desc": "לחצו על כפתור ההתחברות. אשרו את הגדרת VPN כש-macOS מבקש. סיימתם!",
            "troubleshootTitle": "פתרון בעיות",
            "troubleshoot1": "אם macOS חוסם את האפליקציה, עברו להעדפות מערכת > פרטיות ואבטחה ואשרו.",
            "troubleshoot2": "נסו להפעיל מחדש את האפליקציה אם החיבור נופל.",
            "troubleshoot3": "לעזרה, שלחו הודעה ל-@DopplerSupportBot בטלגרם — התמיכה שלנו בבינה מלאכותית זמינה 24/7."
        },
        "telegramSection": {
            "title": "שילוב עם טלגרם",
            "subtitle": "קבלו את הגדרות VPN ונהלו את המנוי שלכם ישירות בטלגרם.",
            "vpnBot": "בוט VPN",
            "vpnBotDesc": "קבלו הגדרות VPN, התחברו לשרתים ונהלו את החשבון שלכם.",
            "supportBot": "בוט תמיכה",
            "supportBotDesc": "תמיכה בבינה מלאכותית 24/7 ב-23 שפות. עזרה מיידית לכל בעיה.",
            "miniApp": "מיני אפ למנויים",
            "miniAppDesc": "הירשמו ונהלו את התוכנית שלכם דרך מיני אפ טלגרם עם תשלומי Stripe מאובטחים."
        },
        "backToGuides": "כל המדריכים",
        "nextStep": "הבא",
        "prevStep": "הקודם"
    },
    "hi": {
        "title": "सेटअप गाइड",
        "subtitle": "कुछ ही मिनटों में कनेक्ट करें। शुरू करने के लिए अपना डिवाइस चुनें।",
        "chooseDevice": "अपना डिवाइस चुनें",
        "android": {
            "title": "Android सेटअप",
            "subtitle": "अपने Android डिवाइस पर Doppler VPN सेट करें",
            "step1Title": "V2RayNG डाउनलोड करें",
            "step1Desc": "Google Play Store से V2RayNG इंस्टॉल करें या GitHub से APK डाउनलोड करें।",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "VPN कॉन्फ़िग प्राप्त करें",
            "step2Desc": "हमारा Telegram बॉट @dopplercreatebot खोलें, \"Connect VPN\" पर टैप करें, सर्वर चुनें और आपको VLESS कॉन्फ़िग लिंक मिलेगा।",
            "step3Title": "कॉन्फ़िग इंपोर्ट करें",
            "step3Desc": "VLESS लिंक को कॉपी करने के लिए लॉन्ग-प्रेस करें। V2RayNG खोलें → + बटन टैप करें → \"Import config from clipboard\" चुनें।",
            "step4Title": "कनेक्ट करें",
            "step4Desc": "कनेक्ट करने के लिए प्ले बटन टैप करें। अनुमति मांगने पर VPN की अनुमति दें। आप अब सुरक्षित हैं!",
            "troubleshootTitle": "समस्या निवारण",
            "troubleshoot1": "अगर कनेक्शन विफल हो, तो बॉट में कोई दूसरा सर्वर आज़माएं।",
            "troubleshoot2": "सुनिश्चित करें कि V2RayNG के लिए बैटरी ऑप्टिमाइज़ेशन बंद है।",
            "troubleshoot3": "मदद के लिए, Telegram पर @DopplerSupportBot को मैसेज करें — हमारा AI सपोर्ट 24/7 उपलब्ध है।"
        },
        "ios": {
            "title": "iOS सेटअप",
            "subtitle": "अपने iPhone या iPad पर Doppler VPN सेट करें",
            "step1Title": "Streisand डाउनलोड करें",
            "step1Desc": "App Store से Streisand इंस्टॉल करें। यह मुफ़्त है और VLESS प्रोटोकॉल को सपोर्ट करता है।",
            "step1AppStore": "App Store",
            "step2Title": "VPN कॉन्फ़िग प्राप्त करें",
            "step2Desc": "हमारा Telegram बॉट @dopplercreatebot खोलें, \"Connect VPN\" पर टैप करें, सर्वर चुनें और आपको VLESS कॉन्फ़िग लिंक मिलेगा।",
            "step3Title": "कॉन्फ़िग इंपोर्ट करें",
            "step3Desc": "VLESS लिंक को कॉपी करने के लिए लॉन्ग-प्रेस करें। Streisand खोलें → + टैप करें → \"Import from clipboard\"। अनुमति मांगने पर VPN कॉन्फ़िगरेशन की अनुमति दें।",
            "step4Title": "कनेक्ट करें",
            "step4Desc": "कनेक्ट करने के लिए टॉगल टैप करें। आपका ट्रैफ़िक अब एन्क्रिप्टेड और सुरक्षित है!",
            "troubleshootTitle": "समस्या निवारण",
            "troubleshoot1": "अगर VPN कनेक्ट नहीं होता, तो कॉन्फ़िग हटाकर दोबारा इंपोर्ट करें।",
            "troubleshoot2": "सुनिश्चित करें कि Streisand को सेटिंग्स > जनरल > VPN में VPN कॉन्फ़िगरेशन जोड़ने की अनुमति है।",
            "troubleshoot3": "मदद के लिए, Telegram पर @DopplerSupportBot को मैसेज करें — हमारा AI सपोर्ट 24/7 उपलब्ध है।"
        },
        "windows": {
            "title": "Windows सेटअप",
            "subtitle": "अपने Windows PC पर Doppler VPN सेट करें",
            "step1Title": "v2rayN डाउनलोड करें",
            "step1Desc": "GitHub से v2rayN डाउनलोड करें। ZIP फ़ाइल निकालें और v2rayN.exe चलाएं।",
            "step1Download": "v2rayN डाउनलोड करें",
            "step2Title": "VPN कॉन्फ़िग प्राप्त करें",
            "step2Desc": "हमारा Telegram बॉट @dopplercreatebot खोलें, \"Connect VPN\" पर टैप करें, सर्वर चुनें और आपको VLESS कॉन्फ़िग लिंक मिलेगा।",
            "step3Title": "कॉन्फ़िग इंपोर्ट करें",
            "step3Desc": "VLESS लिंक कॉपी करें। v2rayN में \"Server\" → \"Import from clipboard\" क्लिक करें या Ctrl+V दबाएं।",
            "step4Title": "कनेक्ट करें",
            "step4Desc": "v2rayN ट्रे आइकन पर राइट-क्लिक करें और \"System proxy\" → \"Set as system proxy\" चुनें। आप कनेक्ट हो गए!",
            "troubleshootTitle": "समस्या निवारण",
            "troubleshoot1": "सुनिश्चित करें कि Windows Defender या आपका एंटीवायरस v2rayN को ब्लॉक नहीं कर रहा।",
            "troubleshoot2": "v2rayN को एडमिनिस्ट्रेटर के रूप में चलाने का प्रयास करें।",
            "troubleshoot3": "मदद के लिए, Telegram पर @DopplerSupportBot को मैसेज करें — हमारा AI सपोर्ट 24/7 उपलब्ध है।"
        },
        "mac": {
            "title": "macOS सेटअप",
            "subtitle": "अपने Mac पर Doppler VPN सेट करें",
            "step1Title": "V2RayXS डाउनलोड करें",
            "step1Desc": "GitHub से V2RayXS डाउनलोड करें या Mac App Store से Streisand इंस्टॉल करें।",
            "step1Download": "V2RayXS डाउनलोड करें",
            "step1AppStore": "Mac App Store",
            "step2Title": "VPN कॉन्फ़िग प्राप्त करें",
            "step2Desc": "हमारा Telegram बॉट @dopplercreatebot खोलें, \"Connect VPN\" पर टैप करें, सर्वर चुनें और आपको VLESS कॉन्फ़िग लिंक मिलेगा।",
            "step3Title": "कॉन्फ़िग इंपोर्ट करें",
            "step3Desc": "VLESS लिंक कॉपी करें। V2RayXS खोलें → \"Import\" → \"From clipboard\"। या Streisand में + टैप करें → \"Import from clipboard\"।",
            "step4Title": "कनेक्ट करें",
            "step4Desc": "कनेक्ट बटन पर क्लिक करें। macOS अनुमति मांगे तो VPN कॉन्फ़िगरेशन की अनुमति दें। हो गया!",
            "troubleshootTitle": "समस्या निवारण",
            "troubleshoot1": "अगर macOS ऐप को ब्लॉक करता है, तो सिस्टम प्रेफ़रेंसेज़ > प्राइवेसी और सिक्योरिटी में जाकर अनुमति दें।",
            "troubleshoot2": "अगर कनेक्शन टूटता है तो ऐप को रीस्टार्ट करें।",
            "troubleshoot3": "मदद के लिए, Telegram पर @DopplerSupportBot को मैसेज करें — हमारा AI सपोर्ट 24/7 उपलब्ध है।"
        },
        "telegramSection": {
            "title": "Telegram इंटीग्रेशन",
            "subtitle": "Telegram में सीधे अपना VPN कॉन्फ़िग प्राप्त करें और अपना सब्सक्रिप्शन प्रबंधित करें।",
            "vpnBot": "VPN बॉट",
            "vpnBotDesc": "VPN कॉन्फ़िगरेशन प्राप्त करें, सर्वर से कनेक्ट करें और अपना अकाउंट प्रबंधित करें।",
            "supportBot": "सपोर्ट बॉट",
            "supportBotDesc": "23 भाषाओं में 24/7 AI सपोर्ट। किसी भी समस्या के लिए तुरंत मदद।",
            "miniApp": "सब्सक्रिप्शन Mini App",
            "miniAppDesc": "हमारे Telegram Mini App के ज़रिए सुरक्षित Stripe भुगतान से सब्सक्राइब करें और अपना प्लान प्रबंधित करें।"
        },
        "backToGuides": "सभी गाइड",
        "nextStep": "अगला",
        "prevStep": "पिछला"
    },
    "id": {
        "title": "Panduan Pengaturan",
        "subtitle": "Terhubung dalam hitungan menit. Pilih perangkat Anda untuk memulai.",
        "chooseDevice": "Pilih perangkat Anda",
        "android": {
            "title": "Pengaturan Android",
            "subtitle": "Siapkan Doppler VPN di perangkat Android Anda",
            "step1Title": "Unduh V2RayNG",
            "step1Desc": "Instal V2RayNG dari Google Play Store atau unduh APK dari GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketuk \"Connect VPN\", pilih server, dan Anda akan menerima tautan konfigurasi VLESS.",
            "step3Title": "Impor Konfigurasi",
            "step3Desc": "Tekan lama tautan VLESS untuk menyalinnya. Buka V2RayNG → ketuk tombol + → pilih \"Import config from clipboard\".",
            "step4Title": "Hubungkan",
            "step4Desc": "Ketuk tombol putar untuk terhubung. Izinkan VPN saat diminta. Anda sekarang terlindungi!",
            "troubleshootTitle": "Pemecahan Masalah",
            "troubleshoot1": "Jika koneksi gagal, coba lokasi server lain di bot.",
            "troubleshoot2": "Pastikan optimasi baterai dinonaktifkan untuk V2RayNG.",
            "troubleshoot3": "Untuk bantuan, kirim pesan ke @DopplerSupportBot di Telegram — dukungan AI kami tersedia 24/7."
        },
        "ios": {
            "title": "Pengaturan iOS",
            "subtitle": "Siapkan Doppler VPN di iPhone atau iPad Anda",
            "step1Title": "Unduh Streisand",
            "step1Desc": "Instal Streisand dari App Store. Gratis dan mendukung protokol VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketuk \"Connect VPN\", pilih server, dan Anda akan menerima tautan konfigurasi VLESS.",
            "step3Title": "Impor Konfigurasi",
            "step3Desc": "Tekan lama tautan VLESS untuk menyalinnya. Buka Streisand → ketuk + → \"Import from clipboard\". Izinkan konfigurasi VPN saat diminta.",
            "step4Title": "Hubungkan",
            "step4Desc": "Ketuk toggle untuk terhubung. Lalu lintas Anda sekarang terenkripsi dan terlindungi!",
            "troubleshootTitle": "Pemecahan Masalah",
            "troubleshoot1": "Jika VPN tidak terhubung, coba hapus dan impor ulang konfigurasi.",
            "troubleshoot2": "Pastikan Streisand memiliki izin untuk menambah konfigurasi VPN di Pengaturan > Umum > VPN.",
            "troubleshoot3": "Untuk bantuan, kirim pesan ke @DopplerSupportBot di Telegram — dukungan AI kami tersedia 24/7."
        },
        "windows": {
            "title": "Pengaturan Windows",
            "subtitle": "Siapkan Doppler VPN di PC Windows Anda",
            "step1Title": "Unduh v2rayN",
            "step1Desc": "Unduh v2rayN dari GitHub. Ekstrak file ZIP dan jalankan v2rayN.exe.",
            "step1Download": "Unduh v2rayN",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketuk \"Connect VPN\", pilih server, dan Anda akan menerima tautan konfigurasi VLESS.",
            "step3Title": "Impor Konfigurasi",
            "step3Desc": "Salin tautan VLESS. Di v2rayN, klik \"Server\" → \"Import from clipboard\" atau tekan Ctrl+V.",
            "step4Title": "Hubungkan",
            "step4Desc": "Klik kanan ikon v2rayN di tray sistem dan pilih \"System proxy\" → \"Set as system proxy\". Anda terhubung!",
            "troubleshootTitle": "Pemecahan Masalah",
            "troubleshoot1": "Pastikan Windows Defender atau antivirus Anda tidak memblokir v2rayN.",
            "troubleshoot2": "Coba jalankan v2rayN sebagai Administrator.",
            "troubleshoot3": "Untuk bantuan, kirim pesan ke @DopplerSupportBot di Telegram — dukungan AI kami tersedia 24/7."
        },
        "mac": {
            "title": "Pengaturan macOS",
            "subtitle": "Siapkan Doppler VPN di Mac Anda",
            "step1Title": "Unduh V2RayXS",
            "step1Desc": "Unduh V2RayXS dari GitHub atau instal Streisand dari Mac App Store.",
            "step1Download": "Unduh V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketuk \"Connect VPN\", pilih server, dan Anda akan menerima tautan konfigurasi VLESS.",
            "step3Title": "Impor Konfigurasi",
            "step3Desc": "Salin tautan VLESS. Buka V2RayXS → \"Import\" → \"From clipboard\". Atau di Streisand, ketuk + → \"Import from clipboard\".",
            "step4Title": "Hubungkan",
            "step4Desc": "Klik tombol hubungkan. Izinkan konfigurasi VPN saat macOS meminta. Selesai!",
            "troubleshootTitle": "Pemecahan Masalah",
            "troubleshoot1": "Jika macOS memblokir aplikasi, buka System Preferences > Privacy & Security dan izinkan.",
            "troubleshoot2": "Coba mulai ulang aplikasi jika koneksi terputus.",
            "troubleshoot3": "Untuk bantuan, kirim pesan ke @DopplerSupportBot di Telegram — dukungan AI kami tersedia 24/7."
        },
        "telegramSection": {
            "title": "Integrasi Telegram",
            "subtitle": "Dapatkan konfigurasi VPN dan kelola langganan Anda langsung di Telegram.",
            "vpnBot": "Bot VPN",
            "vpnBotDesc": "Dapatkan konfigurasi VPN, hubungkan ke server, dan kelola akun Anda.",
            "supportBot": "Bot Dukungan",
            "supportBotDesc": "Dukungan AI 24/7 dalam 23 bahasa. Bantuan instan untuk masalah apa pun.",
            "miniApp": "Mini App Langganan",
            "miniAppDesc": "Berlangganan dan kelola paket Anda melalui Mini App Telegram kami dengan pembayaran Stripe yang aman."
        },
        "backToGuides": "Semua Panduan",
        "nextStep": "Berikutnya",
        "prevStep": "Sebelumnya"
    },
    "ms": {
        "title": "Panduan Persediaan",
        "subtitle": "Berhubung dalam beberapa minit. Pilih peranti anda untuk bermula.",
        "chooseDevice": "Pilih peranti anda",
        "android": {
            "title": "Persediaan Android",
            "subtitle": "Sediakan Doppler VPN pada peranti Android anda",
            "step1Title": "Muat turun V2RayNG",
            "step1Desc": "Pasang V2RayNG dari Google Play Store atau muat turun APK dari GitHub.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketik \"Connect VPN\", pilih pelayan dan anda akan menerima pautan konfigurasi VLESS.",
            "step3Title": "Import Konfigurasi",
            "step3Desc": "Tekan lama pautan VLESS untuk menyalinnya. Buka V2RayNG → ketik butang + → pilih \"Import config from clipboard\".",
            "step4Title": "Sambung",
            "step4Desc": "Ketik butang main untuk bersambung. Benarkan kebenaran VPN apabila diminta. Anda kini dilindungi!",
            "troubleshootTitle": "Penyelesaian Masalah",
            "troubleshoot1": "Jika sambungan gagal, cuba lokasi pelayan lain di bot.",
            "troubleshoot2": "Pastikan pengoptimuman bateri dinyahaktifkan untuk V2RayNG.",
            "troubleshoot3": "Untuk bantuan, hantar mesej ke @DopplerSupportBot di Telegram — sokongan AI kami tersedia 24/7."
        },
        "ios": {
            "title": "Persediaan iOS",
            "subtitle": "Sediakan Doppler VPN pada iPhone atau iPad anda",
            "step1Title": "Muat turun Streisand",
            "step1Desc": "Pasang Streisand dari App Store. Percuma dan menyokong protokol VLESS.",
            "step1AppStore": "App Store",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketik \"Connect VPN\", pilih pelayan dan anda akan menerima pautan konfigurasi VLESS.",
            "step3Title": "Import Konfigurasi",
            "step3Desc": "Tekan lama pautan VLESS untuk menyalinnya. Buka Streisand → ketik + → \"Import from clipboard\". Benarkan konfigurasi VPN apabila diminta.",
            "step4Title": "Sambung",
            "step4Desc": "Ketik togol untuk bersambung. Trafik anda kini disulitkan dan dilindungi!",
            "troubleshootTitle": "Penyelesaian Masalah",
            "troubleshoot1": "Jika VPN tidak bersambung, cuba padam dan import semula konfigurasi.",
            "troubleshoot2": "Pastikan Streisand mempunyai kebenaran untuk menambah konfigurasi VPN di Tetapan > Umum > VPN.",
            "troubleshoot3": "Untuk bantuan, hantar mesej ke @DopplerSupportBot di Telegram — sokongan AI kami tersedia 24/7."
        },
        "windows": {
            "title": "Persediaan Windows",
            "subtitle": "Sediakan Doppler VPN pada PC Windows anda",
            "step1Title": "Muat turun v2rayN",
            "step1Desc": "Muat turun v2rayN dari GitHub. Ekstrak fail ZIP dan jalankan v2rayN.exe.",
            "step1Download": "Muat turun v2rayN",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketik \"Connect VPN\", pilih pelayan dan anda akan menerima pautan konfigurasi VLESS.",
            "step3Title": "Import Konfigurasi",
            "step3Desc": "Salin pautan VLESS. Di v2rayN, klik \"Server\" → \"Import from clipboard\" atau tekan Ctrl+V.",
            "step4Title": "Sambung",
            "step4Desc": "Klik kanan ikon v2rayN di tray sistem dan pilih \"System proxy\" → \"Set as system proxy\". Anda bersambung!",
            "troubleshootTitle": "Penyelesaian Masalah",
            "troubleshoot1": "Pastikan Windows Defender atau antivirus anda tidak menyekat v2rayN.",
            "troubleshoot2": "Cuba jalankan v2rayN sebagai Administrator.",
            "troubleshoot3": "Untuk bantuan, hantar mesej ke @DopplerSupportBot di Telegram — sokongan AI kami tersedia 24/7."
        },
        "mac": {
            "title": "Persediaan macOS",
            "subtitle": "Sediakan Doppler VPN pada Mac anda",
            "step1Title": "Muat turun V2RayXS",
            "step1Desc": "Muat turun V2RayXS dari GitHub atau pasang Streisand dari Mac App Store.",
            "step1Download": "Muat turun V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "Dapatkan Konfigurasi VPN",
            "step2Desc": "Buka bot Telegram kami @dopplercreatebot, ketik \"Connect VPN\", pilih pelayan dan anda akan menerima pautan konfigurasi VLESS.",
            "step3Title": "Import Konfigurasi",
            "step3Desc": "Salin pautan VLESS. Buka V2RayXS → \"Import\" → \"From clipboard\". Atau di Streisand, ketik + → \"Import from clipboard\".",
            "step4Title": "Sambung",
            "step4Desc": "Klik butang sambung. Benarkan konfigurasi VPN apabila macOS meminta. Siap!",
            "troubleshootTitle": "Penyelesaian Masalah",
            "troubleshoot1": "Jika macOS menyekat aplikasi, pergi ke System Preferences > Privacy & Security dan benarkan.",
            "troubleshoot2": "Cuba mulakan semula aplikasi jika sambungan terputus.",
            "troubleshoot3": "Untuk bantuan, hantar mesej ke @DopplerSupportBot di Telegram — sokongan AI kami tersedia 24/7."
        },
        "telegramSection": {
            "title": "Integrasi Telegram",
            "subtitle": "Dapatkan konfigurasi VPN dan urus langganan anda terus di Telegram.",
            "vpnBot": "Bot VPN",
            "vpnBotDesc": "Dapatkan konfigurasi VPN, sambung ke pelayan, dan urus akaun anda.",
            "supportBot": "Bot Sokongan",
            "supportBotDesc": "Sokongan AI 24/7 dalam 23 bahasa. Bantuan segera untuk sebarang masalah.",
            "miniApp": "Mini App Langganan",
            "miniAppDesc": "Langgan dan urus pelan anda melalui Mini App Telegram kami dengan pembayaran Stripe yang selamat."
        },
        "backToGuides": "Semua Panduan",
        "nextStep": "Seterusnya",
        "prevStep": "Sebelumnya"
    },
    "th": {
        "title": "คู่มือการตั้งค่า",
        "subtitle": "เชื่อมต่อได้ในไม่กี่นาที เลือกอุปกรณ์ของคุณเพื่อเริ่มต้น",
        "chooseDevice": "เลือกอุปกรณ์ของคุณ",
        "android": {
            "title": "ตั้งค่า Android",
            "subtitle": "ตั้งค่า Doppler VPN บนอุปกรณ์ Android ของคุณ",
            "step1Title": "ดาวน์โหลด V2RayNG",
            "step1Desc": "ติดตั้ง V2RayNG จาก Google Play Store หรือดาวน์โหลด APK จาก GitHub",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "รับค่าคอนฟิก VPN",
            "step2Desc": "เปิดบอท Telegram ของเรา @dopplercreatebot แตะ \"Connect VPN\" เลือกเซิร์ฟเวอร์ แล้วคุณจะได้รับลิงก์คอนฟิก VLESS",
            "step3Title": "นำเข้าคอนฟิก",
            "step3Desc": "กดค้างที่ลิงก์ VLESS เพื่อคัดลอก เปิด V2RayNG → แตะปุ่ม + → เลือก \"Import config from clipboard\"",
            "step4Title": "เชื่อมต่อ",
            "step4Desc": "แตะปุ่มเล่นเพื่อเชื่อมต่อ อนุญาตสิทธิ์ VPN เมื่อได้รับแจ้ง คุณได้รับการปกป้องแล้ว!",
            "troubleshootTitle": "การแก้ไขปัญหา",
            "troubleshoot1": "หากเชื่อมต่อไม่สำเร็จ ลองเลือกเซิร์ฟเวอร์อื่นในบอท",
            "troubleshoot2": "ตรวจสอบว่าปิดการเพิ่มประสิทธิภาพแบตเตอรี่สำหรับ V2RayNG แล้ว",
            "troubleshoot3": "หากต้องการความช่วยเหลือ ส่งข้อความถึง @DopplerSupportBot บน Telegram — ฝ่ายสนับสนุน AI ของเราพร้อมให้บริการ 24/7"
        },
        "ios": {
            "title": "ตั้งค่า iOS",
            "subtitle": "ตั้งค่า Doppler VPN บน iPhone หรือ iPad ของคุณ",
            "step1Title": "ดาวน์โหลด Streisand",
            "step1Desc": "ติดตั้ง Streisand จาก App Store ฟรีและรองรับโปรโตคอล VLESS",
            "step1AppStore": "App Store",
            "step2Title": "รับค่าคอนฟิก VPN",
            "step2Desc": "เปิดบอท Telegram ของเรา @dopplercreatebot แตะ \"Connect VPN\" เลือกเซิร์ฟเวอร์ แล้วคุณจะได้รับลิงก์คอนฟิก VLESS",
            "step3Title": "นำเข้าคอนฟิก",
            "step3Desc": "กดค้างที่ลิงก์ VLESS เพื่อคัดลอก เปิด Streisand → แตะ + → \"Import from clipboard\" อนุญาตการกำหนดค่า VPN เมื่อได้รับแจ้ง",
            "step4Title": "เชื่อมต่อ",
            "step4Desc": "แตะสวิตช์เพื่อเชื่อมต่อ ทราฟฟิกของคุณถูกเข้ารหัสและปกป้องแล้ว!",
            "troubleshootTitle": "การแก้ไขปัญหา",
            "troubleshoot1": "หาก VPN ไม่เชื่อมต่อ ลองลบและนำเข้าคอนฟิกใหม่",
            "troubleshoot2": "ตรวจสอบว่า Streisand มีสิทธิ์เพิ่มการกำหนดค่า VPN ในการตั้งค่า > ทั่วไป > VPN",
            "troubleshoot3": "หากต้องการความช่วยเหลือ ส่งข้อความถึง @DopplerSupportBot บน Telegram — ฝ่ายสนับสนุน AI ของเราพร้อมให้บริการ 24/7"
        },
        "windows": {
            "title": "ตั้งค่า Windows",
            "subtitle": "ตั้งค่า Doppler VPN บน PC Windows ของคุณ",
            "step1Title": "ดาวน์โหลด v2rayN",
            "step1Desc": "ดาวน์โหลด v2rayN จาก GitHub แตกไฟล์ ZIP และเรียกใช้ v2rayN.exe",
            "step1Download": "ดาวน์โหลด v2rayN",
            "step2Title": "รับค่าคอนฟิก VPN",
            "step2Desc": "เปิดบอท Telegram ของเรา @dopplercreatebot แตะ \"Connect VPN\" เลือกเซิร์ฟเวอร์ แล้วคุณจะได้รับลิงก์คอนฟิก VLESS",
            "step3Title": "นำเข้าคอนฟิก",
            "step3Desc": "คัดลอกลิงก์ VLESS ใน v2rayN คลิก \"Server\" → \"Import from clipboard\" หรือกด Ctrl+V",
            "step4Title": "เชื่อมต่อ",
            "step4Desc": "คลิกขวาที่ไอคอน v2rayN ในถาดระบบ แล้วเลือก \"System proxy\" → \"Set as system proxy\" เชื่อมต่อแล้ว!",
            "troubleshootTitle": "การแก้ไขปัญหา",
            "troubleshoot1": "ตรวจสอบว่า Windows Defender หรือแอนตี้ไวรัสไม่ได้บล็อก v2rayN",
            "troubleshoot2": "ลองเรียกใช้ v2rayN ในฐานะผู้ดูแลระบบ",
            "troubleshoot3": "หากต้องการความช่วยเหลือ ส่งข้อความถึง @DopplerSupportBot บน Telegram — ฝ่ายสนับสนุน AI ของเราพร้อมให้บริการ 24/7"
        },
        "mac": {
            "title": "ตั้งค่า macOS",
            "subtitle": "ตั้งค่า Doppler VPN บน Mac ของคุณ",
            "step1Title": "ดาวน์โหลด V2RayXS",
            "step1Desc": "ดาวน์โหลด V2RayXS จาก GitHub หรือติดตั้ง Streisand จาก Mac App Store",
            "step1Download": "ดาวน์โหลด V2RayXS",
            "step1AppStore": "Mac App Store",
            "step2Title": "รับค่าคอนฟิก VPN",
            "step2Desc": "เปิดบอท Telegram ของเรา @dopplercreatebot แตะ \"Connect VPN\" เลือกเซิร์ฟเวอร์ แล้วคุณจะได้รับลิงก์คอนฟิก VLESS",
            "step3Title": "นำเข้าคอนฟิก",
            "step3Desc": "คัดลอกลิงก์ VLESS เปิด V2RayXS → \"Import\" → \"From clipboard\" หรือใน Streisand แตะ + → \"Import from clipboard\"",
            "step4Title": "เชื่อมต่อ",
            "step4Desc": "คลิกปุ่มเชื่อมต่อ อนุญาตการกำหนดค่า VPN เมื่อ macOS แจ้ง เสร็จแล้ว!",
            "troubleshootTitle": "การแก้ไขปัญหา",
            "troubleshoot1": "หาก macOS บล็อกแอป ไปที่ System Preferences > Privacy & Security แล้วอนุญาต",
            "troubleshoot2": "ลองรีสตาร์ทแอปหากการเชื่อมต่อหลุด",
            "troubleshoot3": "หากต้องการความช่วยเหลือ ส่งข้อความถึง @DopplerSupportBot บน Telegram — ฝ่ายสนับสนุน AI ของเราพร้อมให้บริการ 24/7"
        },
        "telegramSection": {
            "title": "การเชื่อมต่อกับ Telegram",
            "subtitle": "รับค่าคอนฟิก VPN และจัดการการสมัครสมาชิกของคุณได้โดยตรงใน Telegram",
            "vpnBot": "บอท VPN",
            "vpnBotDesc": "รับค่าคอนฟิก VPN เชื่อมต่อกับเซิร์ฟเวอร์ และจัดการบัญชีของคุณ",
            "supportBot": "บอทสนับสนุน",
            "supportBotDesc": "สนับสนุน AI 24/7 ใน 23 ภาษา ช่วยเหลือทันทีสำหรับทุกปัญหา",
            "miniApp": "Mini App สมัครสมาชิก",
            "miniAppDesc": "สมัครสมาชิกและจัดการแผนของคุณผ่าน Mini App Telegram ของเราพร้อมการชำระเงิน Stripe ที่ปลอดภัย"
        },
        "backToGuides": "คู่มือทั้งหมด",
        "nextStep": "ถัดไป",
        "prevStep": "ก่อนหน้า"
    },
    "tr": {
        "title": "Kurulum Rehberi",
        "subtitle": "Dakikalar içinde bağlanın. Başlamak için cihazınızı seçin.",
        "chooseDevice": "Cihazınızı seçin",
        "android": {
            "title": "Android Kurulumu",
            "subtitle": "Android cihazınızda Doppler VPN'i kurun",
            "step1Title": "V2RayNG'yi İndirin",
            "step1Desc": "V2RayNG'yi Google Play Store'dan yükleyin veya APK'yı GitHub'dan indirin.",
            "step1PlayStore": "Google Play Store",
            "step1GitHub": "GitHub APK",
            "step2Title": "VPN Yapılandırmasını Alın",
            "step2Desc": "Telegram botumuzu @dopplercreatebot açın,